### ISSUE TITLE
User's profile

### ISSUE THREAD

**Issue by lokesh1jha** [lokesh1jha/devswad#6]
- basic details
- Address
- Orders

On Nav bar after login will have Hi . User's name (Arrow for drop down )
    - My profile
    - My Order
    - Signout
    - Raise a request

**Comment by ritikprajapat21** [comment]
Hi, @lokesh1jha, I would like to work on this issue

**Comment by lokesh1jha** [comment]
Ok @ritikprajapat21

**Comment by ritikprajapat21** [comment]
I have created the component.
[Screencast from 2024-10-12 18-05-50.webm](https://github.com/user-attachments/assets/27aa9a3a-e4a5-41c9-b268-4c6b74e5c335)

Should I also create the respective pages where the data would be shown?

**Comment by lokesh1jha** [comment]
Take the pull from the master I have made changes. 

Adjustments will be needed accordingly.

After that yes, create those respective pages. Meanwhile also keep that responsive I meant Mobile friendly.
